# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import library_pb2 as library__pb2


class LibraryStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListBooks = channel.unary_unary(
        '/server.Library/ListBooks',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=library__pb2.BookList.FromString,
        )
    self.GetBook = channel.unary_unary(
        '/server.Library/GetBook',
        request_serializer=library__pb2.BookRequest.SerializeToString,
        response_deserializer=library__pb2.Book.FromString,
        )
    self.AddBook = channel.unary_unary(
        '/server.Library/AddBook',
        request_serializer=library__pb2.BookRequest.SerializeToString,
        response_deserializer=library__pb2.Book.FromString,
        )
    self.UpdateBook = channel.unary_unary(
        '/server.Library/UpdateBook',
        request_serializer=library__pb2.BookRequest.SerializeToString,
        response_deserializer=library__pb2.Book.FromString,
        )
    self.DeleteBook = channel.unary_unary(
        '/server.Library/DeleteBook',
        request_serializer=library__pb2.BookRequest.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class LibraryServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ListBooks(self, request, context):
    """ListBooks returns all Books
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBook(self, request, context):
    """GetBook returns book by isbn
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddBook(self, request, context):
    """AddBook allows to add a book
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateBook(self, request, context):
    """UpdateBook allows to update a book
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteBook(self, request, context):
    """DeleteBook deletes book identified by isbn
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_LibraryServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListBooks': grpc.unary_unary_rpc_method_handler(
          servicer.ListBooks,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=library__pb2.BookList.SerializeToString,
      ),
      'GetBook': grpc.unary_unary_rpc_method_handler(
          servicer.GetBook,
          request_deserializer=library__pb2.BookRequest.FromString,
          response_serializer=library__pb2.Book.SerializeToString,
      ),
      'AddBook': grpc.unary_unary_rpc_method_handler(
          servicer.AddBook,
          request_deserializer=library__pb2.BookRequest.FromString,
          response_serializer=library__pb2.Book.SerializeToString,
      ),
      'UpdateBook': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateBook,
          request_deserializer=library__pb2.BookRequest.FromString,
          response_serializer=library__pb2.Book.SerializeToString,
      ),
      'DeleteBook': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteBook,
          request_deserializer=library__pb2.BookRequest.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'server.Library', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
